exclude: 'dist/.*$'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: name-tests-test
# TODO: Add typescript lint
